kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: production-deployment
spec:
  selector:
    matchLabels:
      app: fe-service
      role: be
      env: production
  replicas: 1
  template:
    metadata:
      name: api-deployment
      labels:
        app: fe-service
        role: fe
        env: production
    spec:
      containers:
        - name: node-app
          image: gcr.io/gcr-project/sample:1.0.0
          env:
            - name: MONGOLAB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGOLAB_URI
            # - name: NODE_ENV
            #   value: production
            # - name: HOST_IP
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.podIP
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /interns
              port: 3000
          ports:
            - name: http
              containerPort: 3000