kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: development-staging
spec:
  selector:
    matchLabels:
      app: fe-service
      role: fe
  replicas: 1
  template:
    metadata:
      name: api-deployment
      labels:
        app: fe-service
        role: fe
        env: staging
    spec:
      containers:
        - name: api
          image: gcr.io/gcr-project/sample:1.0.0
          env:
            - name: MONGOLAB_DB
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGOLAB_URI
            - name: NODE_ENV
              value: production
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /interns
              port: 3000
          ports:
            - name: http
              containerPort: 3000