kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: fe-service
      role: be
  replicas: 2
  template:
    metadata:
      name: api-pod
      labels:
        app: fe-service
        role: be
    spec:
      containers:
        - name: node-app
          image: gcr.io/gcr-project/sample:1.0.0
          env:
            - name: MONGOLAB_DB
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGOLAB_URI
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /interns
              port: 3000
          ports:
            - name: http
              containerPort: 3000