apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8160
      targetPort: 8160
  selector:
    app: sample-service
    role: sample
